# Generated by Django 6.0.5 on 2026-05-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compromisso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora')),
                ('tipo', models.CharField(choices=[('PROVA', 'Prova'), ('TRABALHO', 'Trabalho'), ('ATENDIMENTO', 'Atendimento com Professor')], default='PROVA', max_length=20)),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluído')),
            ],
            options={
                'verbose_name': 'Compromisso',
                'verbose_name_plural': 'Compromissos',
            },
        ),
    ]
