# Generated by Django 6.0.5 on 2026-05-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compromisso',
            options={'ordering': ['data_hora'], 'verbose_name': 'Compromisso', 'verbose_name_plural': 'Compromissos'},
        ),
        migrations.AddField(
            model_name='compromisso',
            name='destacar',
            field=models.BooleanField(default=True, verbose_name='Destacar no Calendário'),
        ),
        migrations.AlterField(
            model_name='compromisso',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição/Local'),
        ),
        migrations.AlterField(
            model_name='compromisso',
            name='tipo',
            field=models.CharField(choices=[('PROVA', 'Prova (Vermelho - Crítico)'), ('TRABALHO', 'Trabalho (Amarelo - Importante)'), ('ATIVIDADE', 'Atividade (Verde - Entrega)'), ('ATENDIMENTO', 'Atendimento com Professor (Ciano)'), ('REPOSICAO', 'Reposição de Aula (Azul)'), ('EVENTO', 'Evento / Visita Técnica (Roxo)')], default='PROVA', max_length=20),
        ),
    ]
