# Generated by Django 6.0.5 on 2026-05-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_compromisso_options_compromisso_destacar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromisso',
            name='destacar',
            field=models.BooleanField(default=True, verbose_name='Exibir no Calendário'),
        ),
        migrations.AlterField(
            model_name='compromisso',
            name='tipo',
            field=models.CharField(choices=[('PROVA', 'Prova (Vermelho)'), ('TRABALHO', 'Trabalho (Amarelo)'), ('ATIVIDADE', 'Atividade (Verde)'), ('ATENDIMENTO', 'Atendimento com Professor (Ciano)'), ('REPOSICAO', 'Reposição de Aula (Azul)'), ('EVENTO', 'Evento / Visita Técnica (Roxo)')], default='PROVA', max_length=20),
        ),
    ]
