# Generated by Django 6.0.5 on 2026-05-22 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_compromisso_destacar_alter_compromisso_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisso',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilizador'),
        ),
        migrations.AlterField(
            model_name='compromisso',
            name='destacar',
            field=models.BooleanField(default=True, verbose_name='Exibir no Painel'),
        ),
        migrations.AlterField(
            model_name='compromisso',
            name='tipo',
            field=models.CharField(choices=[('PROVA', 'Prova'), ('TRABALHO', 'Trabalho'), ('ATIVIDADE', 'Atividade'), ('ATENDIMENTO', 'Atendimento com Professor'), ('REPOSICAO', 'Reposição de Aula'), ('EVENTO', 'Evento / Visita Técnica')], default='PROVA', max_length=20),
        ),
    ]
